<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find yozakura_display)/robot/config.xacro" />

	<xacro:macro 	name="armjack_left" 
								params="parent suffix">

  <joint name="${joint_armLinear_left_A}_${suffix}" type="revolute">
    <axis xyz="0 0 1"/>
    <limit 	lower="${DEG2RAD*armYawAngle_min}" effort="1000.0"  		
						upper="${DEG2RAD*armYawAngle_max}" velocity="0.5"/>
    <origin rpy="0 0 0" 
						xyz="0 ${-armLinear_frame_length} 0"/>
    <parent link="${parent}"/>
    <child link="${arm_linear_frame_left_A}_${suffix}"/>
  </joint>

	<link name="${arm_linear_frame_left_A}_${suffix}">
		<visual>
			<origin rpy="0 0 0" 
							xyz="0 ${armLinear_frame_length/2.0} 0"/>	
			<geometry>
				<mesh filename="${robotPackagePath}/${modelDataResourseFolder}/arm_linear_frame.stl"/>
			</geometry>
		</visual>
	</link>

  <joint name="${joint_armLinear_left_B}_${suffix}" type="revolute">
    <axis xyz="0 0 1"/>
    <limit 	lower="${DEG2RAD*armYawAngle_min}" effort="1000.0"  		
						upper="${DEG2RAD*armYawAngle_max}" velocity="0.5"/>
    <origin rpy="0 0 0" 
						xyz="0 ${armLinear_frame_length} 0"/>
    <parent link="${arm_linear_frame_left_A}_${suffix}"/>
    <child link="${arm_linear_frame_left_B}_${suffix}"/>
  </joint>

	<link name="${arm_linear_frame_left_B}_${suffix}">
		<visual>
			<origin rpy="0 0 0" 
							xyz="0 ${-armLinear_frame_length/2.0} 0"/>	
			<geometry>
				<mesh filename="${robotPackagePath}/${modelDataResourseFolder}/arm_linear_frame.stl"/>
			</geometry>
		</visual>
	</link>
	</xacro:macro>
</robot>









